Book/urls.py
from django.conf.urls import include , url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log.urls')),
]

log/urls.py
from django.conf.urls import url , include
from django.contrib.auth.views import  login
#from django.contrib.auth.decorators import login_required

from log.views import logout_page, register_page, main_page, detail, post


urlpatterns = [
    url(r'^booklist/(?P<book_id>[0-9]+)/$', detail, name='detail'),
    url(r'^post/$', post),
    #url(r'^post/$', login_required(post)),
	url(r'^login/$', login, name='login'),
	url(r'^logout$', logout_page),
	url(r'^register/$', register_page),
    url(r'^$', main_page, name='home'),
]

log/models.py
from django.db import models

class Book(models.Model):
    Name = models.CharField( max_length = 100 )
    Link = models.CharField( max_length = 200 )
    Description = models.CharField(max_length = 500)
    pub_date = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.Name

log/forms.py
from django import forms
from .models import Book
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget = forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)', widget =forms.PasswordInput())



class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('Name', 'Link', 'Description', )


        def clean_Name(self):
            Name = self.cleaned_date['Name']
            Link = self.cleaned_date['Link']
            Description = self.cleaned_date['Description']
            #Image = self.cleaned_data.get('Image', False)


def clean_password2(self):
    if 'password1' in self.cleaned_data:
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 == password2:
            return password2
    raise forms.ValidationError('Passwords do not match.')


def clean_username(self):
    username = self.cleaned_data['username']
    if not re.search(r'^\w+$', username):
        raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
    try:
        User.objects.get(username=username)
    except ObjectDoesNotExist:
        return username
    raise forms.ValidationError('Username is already taken.')

log/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.template import Context
from django.template.loader import get_template
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
#from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .forms import *
from .models import Book

# Create your views here.


def index(request):
    return HttpResponse("Book added :) ")


def detail(request, book_id):
    book =  get_object_or_404(Book, pk= book_id)
    return render(request, 'booklist/detailview.html', { 'Book' : book })



def main_page(request):
    books = Book.objects.order_by('-pub_date')[:10]
    template = get_template('main_page.html')
    variables = Context({ 'user': request.user,'Books' : books })
    output = template.render(variables)
    return HttpResponse(output)



def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')


#@csrf_protect
def register_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],password=form.cleaned_data['password1'],email=form.cleaned_data['email'])
            return render(request, 'registration/success.html')
    form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})



#@login_required()
@login_required(login_url='login')
def post(request):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            # print form
            book = form.save()
            book.author = request.user
            book.published_date = timezone.now()
            book.save()
            return HttpResponseRedirect('/')
    form = BookForm()
    return render(request, 'booklist/post.html', {'form': form})

log/templates/base.html
{% load staticfiles %}
<!DOCTYPE>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <nav>
        <ul>
            {% if user.username %}
                <p>{{ user.username  }} </p>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="/logout">logout</a></li>
                <li><a href="/post">Post</a></li>
            {% else %}
                <li> <a href="/register/">register</a></li>
                <li> <a href="/login/">Login</a></li>
            {% endif %}
            <li><a href="/">Home</a></li>
        </ul>

    </nav>
    {% block content %}{% endblock %}
</body>
</html>

log/templates/booklist/detailview.html
{% extends "base.html" %}

{%block content %}
<div  class="container detail">
	<h1>{{ Book.Name }}</h1>
	<p>published date: {{ Book.pub_date }}</p>
	Link: <a href="{{ Book.Link }}"> {{ Book.Name }}</a>
	<p>Description: {{ Book.Description }} </p>

</div>

{% endblock %}

log/templates/booklist/listview.html
<div class="container">
{% if Books %}
    <ul>
    {% for Book in Books %}
        <a href="/booklist/{{ Book.id }}/"> <li class="list">{{ Book.Name }} </li></a>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

log/templates/booklist/post.html
{% extends 'base.html' %}

{% block content %}

<div >
    <form class="post" method="POST" action="." enctype="multipart/form-data" >
        <h2 class="posthead" >Add new post</h2>
        <div >
            <label for="id_Name"> Name </label>
            <input class="form-input" type="text" name="Name" id="id_Name" placeholder="Name" required=""  >
        </div>
        <div >
            <label for="id_Link"> Link </label>
            <input class="form-input" type="text" name="Link" id="id_Link" placeholder="Link" required=""  >
        </div>
        <div >
            <label for="id_Description"> Description </label>
            <textarea class="form-input" type="text" name="Description" id="id_Description" placeholder="Description" required=""  ></textarea>
        </div>
        <button type="submit" class="btn">Post</button>
        {% csrf_token %}

    </form>
</div>

{% endblock %}

log/templates/main_page.html
{%extends "base.html" %}
{%block title %}Welcome to Django store{% endblock %}
{%block head %}Welcome to Django store{% endblock %}
{%block content %}


    {% include "booklist/listview.html" %}


{% endblock %}